image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Kurtosis
    command: |
      kurtosis engine restart
      kurtosis run github.com/fake-package/fake-package-purely-for-analytics || kurtosis clean -a
      code README.md
      source <(kurtosis completion bash)
      echo "source <(kurtosis completion bash)" >> ~/.bashrc
      clear  

ports:
  - name: Kurtosis Engine Grpc Listen
    port: 9710
    onOpen: ignore
  - name: Kurtosis Engine Grpc Proxy Listen
    port: 9710
    onOpen: ignore
  

vscode:
  extensions:
    - Kurtosis.kurtosis-extension
